version: "3.8"

services:
  vote:
    image: fabianhilares852/examen-vote1
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip-172-31-83-211]
    depends_on:
      - redis
    ports:
      - "5000:80"
    networks:
      - back-tier

  result:
    image: fabianhilares852/examen-result1
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip-172-31-35-33]
    ports:
      - "5001:80"
    networks:
      - back-tier

  worker:
    image: fabianhilares852/examen-worker1
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip-172-31-80-252]
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: fabianhilares852/examen-redis1
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip-172-31-83-133]
    ports:
      - "6379:6379"
    networks:
      - back-tier

  db:
    image: fabianhilares852/examen-db1
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == ip-172-31-90-70]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - back-tier

volumes:
  postgres_data:

networks:
  back-tier:
    driver: overlay
